#Sample config

graph_data: ../../code/out/graph.csv
content_ldb: ../../code/out/content.ldb
feature_config: ../../code/features.yaml
vid_file: sample/chosen_ids.json
filterlists: ../../filterlists
parent_limit: 10

model:  sample/model_1.joblib

result_dir: results_struct

mutation_style:
  - node_addition
  - storage_removal
  - redirect_removal
  - url_obfuscation