#Sample config

graph_data: graph.csv
content_ldb: content.ldb
feature_config: features.yaml
vid_file: chosen_ids.json
filterlists: filterlists
parent_limit: 10

model:  model_0.joblib

result_dir: results_struct

mutation_style:
  - node_addition
  - storage_removal
  - redirect_removal
  - url_obfuscation